tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/services"
brew "curl"
brew "git"
brew "nodenv"
brew "tree"
brew "pass"
brew "postgresql", restart_service: true
brew "pyenv"
brew "rbenv"
brew "rename"
brew "wget"
